### ISSUE TITLE
Which linux distribution is the best plantform to use mazu-sim?

### ISSUE THREAD

**Issue by spacefan** [octoberskyTW/mazu-sim#8]
I have compiled the master rep on Ubuntu 16.04, CentOS 7.6 and Manjaro 18.1, but, none of them successed. So, which linux distribution (and release version) is the best platform to compile mazu-sim?

**Comment by spacefan** [comment]
Nobady to care about this issue except me?

**Comment by erickitten** [comment]
Ok, I haven't worked on the code for quite a while...
Are you having trouble compiling, running or get the correct result?
Are there any error messages?

**Comment by j8xixo12** [comment]
Sorry for late reply...
I compiled and run this code on Ubuntu 18.04
Maybe problem is  the NASA-Trick version?

**Comment by j8xixo12** [comment]
@spacefan My NASA-Trick version is 17.5 Dev

**Comment by spacefan** [comment]
Yes, its the problem of NASA-Trick version, I suggest you to update readme file **2. Third-Party Installation**, or users such as me will be confused by error compiling messages.

**Comment by j8xixo12** [comment]
Got it!  Thanks for your suggestion!

**Comment by j8xixo12** [comment]
@spacefan If there is any suggestions , no matter what, such like coding style, architecture of simulatior...etc, please  tell me!

It seems like you are the only user of mazu-sim lol...
So far, I knew mazu-sim there are still many place need to be improved, performance, solver, input file...etc

I will find time to deal with it!

**Comment by spacefan** [comment]
That would be great! I just begin with CADAC++, if there is forward issues, i'll report for you.
